---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "kikizizinazi", Texture = "gradient_bgd", Y = 0.3, Width = 443, Height = 10 },
}

---@type Panel
function RageUI.RenderSprite(Dictionary, Texture, Index)
    local CurrentMenu = RageUI.CurrentMenu
    if CurrentMenu() and (CurrentMenu.Index == Index) then
        if CurrentMenu ~= nil then
            if CurrentMenu() then
                RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + RageUI.ItemOffset + (RageUI.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
                RageUI.StatisticPanelCount = RageUI.StatisticPanelCount + 1
            end
        end
    end
end